# Generated by Django 5.0 on 2026-01-15 20:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=50)),
                ('clinical_history', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='pets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
