# Generated by Django 5.2.10 on 2026-01-18 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='pet_name',
        ),
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='species',
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='pet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_records', to='pages.pet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinicalrecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pets/'),
        ),
    ]
