# Generated by Django 5.2.10 on 2026-01-18 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_clinicalrecord_pet_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalrecord',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='pages.pet'),
        ),
    ]
