# Generated by Django 5.2.10 on 2026-01-18 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_clinicalrecord_pet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='pet',
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='pet_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='species',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('caballo', 'Caballo')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
