# Generated by Django 5.2.10 on 2026-01-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_clinicalrecord_pet_clinicalrecord_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalrecord',
            name='moquillo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='moquillo_doses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='parvovirus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='parvovirus_doses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='rabia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='rabia_doses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
