# Generated by Django 5.2.10 on 2026-01-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_clinicalrecord_moquillo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalrecord',
            name='age',
            field=models.PositiveIntegerField(default=1, help_text='Edad en años'),
            preserve_default=False,
        ),
    ]
