# Generated by Django 5.2.10 on 2026-01-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_clinicalrecord_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalrecord',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
