# Generated by Django 5.2.10 on 2026-01-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_remove_message_read_message_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='attachment',
        ),
    ]
